const MAX_POINTS = 10;
const MAX_QUESTIONS = 10;
const MAX_SCORE = MAX_POINTS * MAX_QUESTIONS;
const REQUIRED_SCORE = MAX_SCORE / 2;

export {
    MAX_POINTS,
    MAX_QUESTIONS,
    MAX_SCORE,
    REQUIRED_SCORE
}